### ISSUE TITLE
Generate API bindings automatically

### ISSUE THREAD

**Issue by fzyzcjy** [ethanblake4/flutter_eval#14] opened 2022-10-19 12:32 UTC
Looking at https://github.com/ethanblake4/flutter_eval/commit/7d1cf73f8fcfa60041098c600cfb9758272b426d, I guess these bindings are written manually by hand? If so, maybe we can generate them automatically. For example, we can utilize the Dart Analyzer to scan flutter framework code, then we can get info for each field/method/etc. Then we just generate those BridgeParameter etc.

**Comment by ethanblake4** [comment] 2022-10-19 22:12
Duplicate of https://github.com/ethanblake4/dart_eval/issues/20

**Closed by ethanblake4** 2022-10-19 22:12 UTC
